import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df = pd.read_csv("Titanic-Dataset.csv")
print("First Five Rows")
print(df.head())
print("\nDataset Information")
print(df.info())
print("\nSummary Statistics")
print(df.describe(include='all'))
print("\nMissing Values")
print(df.isnull().sum())
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
df[numeric_columns].hist(figsize=(12,10))
plt.suptitle("Histograms of Numerical Features")
plt.tight_layout()
plt.show()
for col in numeric_columns:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()
numeric_df = df.select_dtypes(include=['number'])
plt.figure(figsize=(10,8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()
sns.pairplot(df[['Age','Fare','Pclass','Survived']].dropna(),hue='Survived')
plt.show()
plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df)
plt.title("Passenger Survival Count")
plt.show()
plt.figure(figsize=(6,4))
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()
plt.figure(figsize=(6,4))
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()
fig = px.histogram(df,x="Age",color="Survived",title="Age Distribution by Survival")
fig.show()
